from setuptools import setup

setup(name='juniper-package',
      version='0.1',
      description='JWST exoplanet time-series pipeline',
      long_description="Pipeline for handling James Webb Space Telescope time-series observations of exoplanet transits and eclipses.",
      author='Abby Boehm',
      packages=['juniper',
                'juniper.util',
                'juniper.config',
                'juniper.stage1',
                'juniper.stage2',
                'juniper.stage3',
                'juniper.stage4',
                'juniper.stage5',
                'juniper.stage6',],
      python_requires='>=3.8.0',
      install_requires=['scipy>=1.8.0', 'numpy', 'jwst>=1.10.0', 'tqdm',
                        'matplotlib', 'batman-package', 'astropy', 'corner',
                        'emcee', 'exotic-ld', 'photutils', 'xarray', 'mc3',
                        'setuptools<=82.0.0'],
      zip_safe=False)
